Minor bug fixes and some indentation

diff --git a/scripts/s3fs-manager b/scripts/s3fs-manager
--- a/scripts/s3fs-manager
+++ b/scripts/s3fs-manager
@@ -83,7 +83,7 @@ done;
 
 case $action in
 	mount)
-		MOUNTPOINT=$(awk '{print $3' $mountLocation)
+		MOUNTPOINT=$(awk '{print $3}' $mountLocation)
 		echo $MOUNTPOINT | egrep -q "^/root|^/$"
 		if [ $? -eq 0 ]; then
 			echo "Invalid mountpoint"
@@ -132,15 +132,16 @@ case $action in
         			continue
         		fi;
 
-        		mount | grep -q $MOUNTPOINT 2>/dev/null
-        		if [ $? -ne 0 ]; then
-                	/bin/bash ~/.s3fs/mounts/$bucketname
+				mount | grep -q $MOUNTPOINT 2>/dev/null
+				if [ $? -ne 0 ]; then
+					/bin/bash ~/.s3fs/mounts/$bucketname
+				fi
 
-                if [ $? -eq 0 ]; then
-                	echo -e "\n $bucketname - MOUNTED on $MOUNTPOINT"
+				if [ $? -eq 0 ]; then
+					echo -e "\n $bucketname - MOUNTED on $MOUNTPOINT"
                 else
-                	echo -e "\n Failed to mount $bucketname"
-                	continue
+					echo -e "\n Failed to mount $bucketname"
+					continue
                 fi;
             fi;
 		done;
@@ -148,17 +149,17 @@ case $action in
 
 	umountall)
 		for bucketname in $(ls -1 ~/.s3fs/mounts/); do
-        		MOUNTPOINT=$(awk '{print $3}' ~/.s3fs/mounts/$bucketname )
-        		mount | grep -q $MOUNTPOINT 2>/dev/null
-        		if [ $? -eq 0 ]; then
-                	fusermount -u $MOUNTPOINT
-      			if [ $? - ne 0 ]; then
-      				echo -e "\n $bucketname - UNMOUNTED from $MOUNTPOINT"
-                else
-                	echo -e "\n Cannot unmount $bucketname"
-                	continue
-                fi;
-            fi;
+				MOUNTPOINT=$(awk '{print $3}' ~/.s3fs/mounts/$bucketname )
+				mount | grep -q $MOUNTPOINT 2>/dev/null
+				if [ $? -eq 0 ]; then
+					fusermount -u $MOUNTPOINT
+				if [ $? -ne 0 ]; then
+					echo -e "\n $bucketname - UNMOUNTED from $MOUNTPOINT"
+				else
+					echo -e "\n Cannot unmount $bucketname"
+					continue
+				fi;
+			fi;
 		done;
 	;;
 
